// Hard level questions - English (Adult)
// Challenging questions for teens and adults

const hardRiddles = [
    { q: "I have cities, but no houses live there. I have mountains, but no trees grow there. I have water, but no fish swim there. What am I?", a: "A map", wrong: ["A painting", "A dream"] },
    { q: "The more you take, the more you leave behind. What am I?", a: "Footsteps", wrong: ["Memories", "Photographs"] },
    { q: "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", a: "An echo", wrong: ["A ghost", "A shadow"] },
    { q: "I can be cracked, made, told, and played. What am I?", a: "A joke", wrong: ["An egg", "A code"] },
    { q: "I have keys but no locks. I have space but no room. You can enter but you can't go inside. What am I?", a: "A keyboard", wrong: ["A piano", "A parking lot"] },
    { q: "What disappears as soon as you say its name?", a: "Silence", wrong: ["Darkness", "A secret"] },
    { q: "The person who makes it, sells it. The person who buys it never uses it. The person who uses it never knows they're using it. What is it?", a: "A coffin", wrong: ["A gift", "Medicine"] },
    { q: "I am not alive, but I grow. I don't have lungs, but I need air. I don't have a mouth, but water kills me. What am I?", a: "Fire", wrong: ["Rust", "Mold"] },
    { q: "What can travel around the world while staying in a corner?", a: "A stamp", wrong: ["A spider", "A compass"] },
    { q: "I have a head and a tail but no body. What am I?", a: "A coin", wrong: ["A snake", "A comet"] },
    { q: "What has 13 hearts but no other organs?", a: "A deck of cards", wrong: ["A hospital", "A love poem"] },
    { q: "What gets broken without being held?", a: "A promise", wrong: ["A heart", "A record"] },
    { q: "What can you hold in your right hand but never in your left?", a: "Your left elbow", wrong: ["Your right eye", "Your left hand"] },
    { q: "What has a bottom at the top?", a: "Your legs", wrong: ["A mountain", "A bottle"] },
    { q: "What word in the English language does the following: the first two letters signify a male, the first three letters signify a female, the first four letters signify a great, while the entire word signifies a great woman?", a: "Heroine", wrong: ["Heroism", "Heritage"] },
    { q: "I am taken from a mine, and shut up in a wooden case, from which I am never released, and yet I am used by almost everyone. What am I?", a: "Pencil lead", wrong: ["Coal", "A diamond"] },
    { q: "What English word has three consecutive double letters?", a: "Bookkeeper", wrong: ["Committee", "Mississippi"] },
    { q: "Forward I am heavy, but backward I am not. What am I?", a: "The word 'ton'", wrong: ["A truck", "An anchor"] },
    { q: "What occurs once in a minute, twice in a moment, but never in a thousand years?", a: "The letter M", wrong: ["A heartbeat", "A blink"] },
    { q: "A man is pushing his car along a road when he comes to a hotel. He shouts 'I'm bankrupt!' Why?", a: "He's playing Monopoly", wrong: ["He lost his wallet", "His car broke down"] },
    { q: "What can fill a room but takes up no space?", a: "Light", wrong: ["Sound", "Air"] },
    { q: "The eight of us go forth, not back, to protect our king from a foe's attack. What are we?", a: "Chess pawns", wrong: ["Knights", "Bodyguards"] },
    { q: "What is seen in the middle of March and April that can't be seen at the beginning or end of either month?", a: "The letter R", wrong: ["Spring", "Easter"] },
    { q: "I have branches, but no fruit, trunk, or leaves. What am I?", a: "A bank", wrong: ["A river", "A family tree"] },
    { q: "What five-letter word becomes shorter when you add two letters to it?", a: "Short", wrong: ["Small", "Brief"] },
    { q: "What begins with T, finishes with T, and has T in it?", a: "A teapot", wrong: ["A tent", "A test"] },
    { q: "A man looks at a painting and says 'Brothers and sisters I have none, but that man's father is my father's son.' Who is in the painting?", a: "His son", wrong: ["Himself", "His father"] },
    { q: "What has one eye but cannot see?", a: "A needle", wrong: ["A cyclops", "A camera"] },
    { q: "What belongs to you but is used more by others?", a: "Your name", wrong: ["Your phone", "Your car"] },
    { q: "I am always hungry and will die if not fed, but whatever I touch will soon turn red. What am I?", a: "Fire", wrong: ["Acid", "Rust"] },
    { q: "What goes through cities and fields but never moves?", a: "A road", wrong: ["A river", "The wind"] },
    { q: "What has many teeth but cannot bite?", a: "A comb", wrong: ["A saw", "A zipper"] },
    { q: "I fly without wings, I cry without eyes. Whenever I go, darkness flies. What am I?", a: "The sun", wrong: ["The wind", "A candle"] },
    { q: "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?", a: "A river", wrong: ["A clock", "A volcano"] },
    { q: "I have four fingers and a thumb but I'm not alive. What am I?", a: "A glove", wrong: ["A robot hand", "A statue"] },
    { q: "What word is spelled incorrectly in every dictionary?", a: "Incorrectly", wrong: ["Misspelled", "Wrong"] },
    { q: "If you drop me, I'm sure to crack, but give me a smile and I'll always smile back. What am I?", a: "A mirror", wrong: ["An egg", "A phone screen"] },
    { q: "The more of this there is, the less you see. What is it?", a: "Darkness", wrong: ["Fog", "Smoke"] },
    { q: "What invention lets you look right through a wall?", a: "A window", wrong: ["X-ray", "A periscope"] },
    { q: "What has words but never speaks?", a: "A book", wrong: ["A painting", "A sign"] },
    { q: "David's father has three sons: Snap, Crackle, and ___?", a: "David", wrong: ["Pop", "Rice"] },
    { q: "What building has the most stories?", a: "A library", wrong: ["A skyscraper", "A hotel"] },
    { q: "What tastes better than it smells?", a: "A tongue", wrong: ["Cheese", "Coffee"] },
    { q: "What two things can you never eat for breakfast?", a: "Lunch and dinner", wrong: ["Salt and pepper", "Bread and butter"] },
    { q: "What month of the year has 28 days?", a: "All of them", wrong: ["February", "None"] },
    { q: "A girl fell off a 50-foot ladder but didn't get hurt. How?", a: "She fell off the bottom step", wrong: ["She landed in water", "She had a parachute"] },
    { q: "What goes up and down but doesn't move?", a: "A staircase", wrong: ["Temperature", "An elevator"] },
    { q: "How many letters are in 'the alphabet'?", a: "Eleven", wrong: ["Twenty-six", "Three"] },
    { q: "If two's company and three's a crowd, what are four and five?", a: "Nine", wrong: ["A party", "Too many"] },
    { q: "Three doctors said that Robert was their brother. Robert said he had no brothers. Who's lying?", a: "Nobody — the doctors were his sisters", wrong: ["Robert", "The doctors"] },
    { q: "What has a ring but no finger?", a: "A telephone", wrong: ["Saturn", "A boxing ring"] },
    { q: "I turn once, what is out will not get in. I turn again, what is in will not get out. What am I?", a: "A key", wrong: ["A door", "A valve"] },
    { q: "People make me, save me, change me, raise me. What am I?", a: "Money", wrong: ["Children", "Laws"] },
    { q: "What breaks yet never falls, and what falls yet never breaks?", a: "Day and night", wrong: ["Waves and rain", "Hearts and dreams"] },
    { q: "I am lighter than a feather, yet the strongest person can't hold me for more than 5 minutes. What am I?", a: "Breath", wrong: ["A thought", "A secret"] },
    { q: "What runs all around a backyard, yet never moves?", a: "A fence", wrong: ["A sprinkler", "A dog"] },
    { q: "A bus driver goes the wrong way on a one-way street. He passes the cops but they don't stop him. Why?", a: "He was walking", wrong: ["He was off duty", "It was an emergency"] },
    { q: "What is it that given one, you'll have either two or none?", a: "A choice", wrong: ["A coin flip", "A twin"] },
    { q: "What do you answer even though it never asks you a question?", a: "A doorbell", wrong: ["A phone", "A test"] },
    { q: "If you have me, you want to share me. If you share me, you haven't got me. What am I?", a: "A secret", wrong: ["Love", "Money"] },
    { q: "What can you catch but never throw?", a: "A cold", wrong: ["A bus", "A glance"] },
    { q: "When you have me, you immediately feel like sharing me. But if you share me, you no longer have me.", a: "A secret", wrong: ["A feeling", "An idea"] },
    { q: "What has a neck but no head?", a: "A bottle", wrong: ["A guitar", "A shirt"] },
    { q: "What goes up but never comes down?", a: "Your age", wrong: ["A balloon", "Smoke"] },
    { q: "It stalks the countryside with ears that can't hear. What is it?", a: "Corn", wrong: ["A scarecrow", "A fox"] },
    { q: "What can you break, even if you never pick it up or touch it?", a: "A promise", wrong: ["A heart", "A law"] },
    { q: "What question can you never answer yes to?", a: "Are you asleep?", wrong: ["Are you dead?", "Are you lying?"] },
    { q: "I am an odd number. Take away a letter and I become even. What number am I?", a: "Seven", wrong: ["Nine", "Eleven"] },
    { q: "If there are three apples and you take away two, how many do you have?", a: "Two", wrong: ["One", "Three"] },
    { q: "What has legs but doesn't walk?", a: "A table", wrong: ["A spider", "A centipede"] },
    { q: "What has hands but can't clap?", a: "A clock", wrong: ["A statue", "A glove"] },
    { q: "What starts with E, ends with E, and has one letter in it?", a: "An envelope", wrong: ["The word eye", "An eagle"] },
    { q: "Where does today come before yesterday?", a: "In the dictionary", wrong: ["In Australia", "Nowhere"] },
    { q: "What word becomes shorter when you add two letters?", a: "Short", wrong: ["Thin", "Little"] },
    { q: "What room has no doors or windows?", a: "A mushroom", wrong: ["A chatroom", "A tomb"] },
    { q: "I shave every day, but my beard stays the same. What am I?", a: "A barber", wrong: ["A razor", "A mannequin"] },
    { q: "What can you keep after giving it to someone?", a: "Your word", wrong: ["A gift", "Advice"] },
    { q: "How can a man go 8 days without sleep?", a: "He sleeps at night", wrong: ["He's an insomniac", "He uses caffeine"] },
    { q: "I am full of holes but I still hold water. What am I?", a: "A sponge", wrong: ["A net", "A colander"] },
    { q: "What gets wetter the more it dries?", a: "A towel", wrong: ["A sponge", "Sand"] },
    { q: "Where do fish keep their money?", a: "In a riverbank", wrong: ["In a shell", "In seaweed"] },
    { q: "What kind of band never plays music?", a: "A rubber band", wrong: ["A headband", "A wristband"] },
    { q: "What has ears but cannot hear?", a: "A cornfield", wrong: ["A statue", "A teddy bear"] },
    { q: "What coat is best put on wet?", a: "A coat of paint", wrong: ["A raincoat", "A trench coat"] },
    { q: "What has 88 keys but can't open a single door?", a: "A piano", wrong: ["A locksmith", "A janitor"] },
    { q: "What has a thumb and four fingers but is not a hand?", a: "A glove", wrong: ["A starfish", "A robot"] },
    { q: "What do Alexander the Great and Winnie the Pooh have in common?", a: "The same middle name", wrong: ["Both are fictional", "Both are British"] },
    { q: "What falls but never gets hurt?", a: "Rain", wrong: ["Snow", "A leaf"] },
    { q: "If a red house is made of red bricks, and a yellow house of yellow bricks, what is a greenhouse made of?", a: "Glass", wrong: ["Green bricks", "Plants"] },
    { q: "What's always found on the ground but never gets dirty?", a: "A shadow", wrong: ["Grass", "Dirt"] },
    { q: "A man who was outside in the rain without an umbrella or hat didn't get a single hair on his head wet. Why?", a: "He was bald", wrong: ["He was inside a car", "It was light rain"] },
    { q: "What goes in a birdbath but never gets wet?", a: "The bird's shadow", wrong: ["A rubber duck", "Leaves"] },
    { q: "What is 3/7 chicken, 2/3 cat, and 2/4 goat?", a: "Chicago", wrong: ["A chimera", "A farm"] },
    { q: "I exist when there is light, but direct light kills me. What am I?", a: "A shadow", wrong: ["A vampire", "A photograph"] },
    { q: "What do you throw out when you want to use it but take in when you don't want to use it?", a: "An anchor", wrong: ["A fishing line", "A boomerang"] },
    { q: "What English word retains the same pronunciation even after you take away four of its five letters?", a: "Queue", wrong: ["Aisle", "Knife"] },
    { q: "First you eat me, then you get eaten. What am I?", a: "A fishhook", wrong: ["Poison", "A seed"] },
    { q: "What can be swallowed, but can also swallow you?", a: "Pride", wrong: ["Water", "Darkness"] },
    { q: "If two is a pair and three is a crowd, what are four and five?", a: "Nine", wrong: ["A group", "Too many"] },
    { q: "I am not alive, yet I grow. I have no lungs, yet I need air. What am I?", a: "Fire", wrong: ["A crystal", "A balloon"] },
    { q: "I follow you everywhere but you can never catch me. What am I?", a: "Your shadow", wrong: ["Your reflection", "Time"] },
    { q: "A cowboy rides into town on Friday, stays for three days, and leaves on Friday. How?", a: "Friday is the horse's name", wrong: ["He time-traveled", "It was a different Friday"] },
    { q: "What disappears the moment you start looking for it?", a: "What you forgot", wrong: ["A ghost", "Darkness"] },
    { q: "What can be measured but has no length, width, or height?", a: "Temperature", wrong: ["Time", "Sound"] },
    { q: "How many of each animal did Moses take on the ark?", a: "None — it was Noah", wrong: ["Two", "Seven"] },
    { q: "I have no life, but I can die. What am I?", a: "A battery", wrong: ["A lightbulb", "A candle"] },
    { q: "What is always in front of you but can't be seen?", a: "The future", wrong: ["Air", "Destiny"] },
    { q: "What has a face and two hands but no arms or legs?", a: "A clock", wrong: ["A doll", "A playing card"] },
    { q: "What can you hold without touching it?", a: "A conversation", wrong: ["A thought", "Your breath"] },
    { q: "What is black when you buy it, red when you use it, and grey when you throw it away?", a: "Charcoal", wrong: ["A matchstick", "A candle"] },
    { q: "I have no doors but I have keys. I have no rooms but I have space. You can enter but you can't leave. What am I?", a: "A keyboard", wrong: ["A maze", "The internet"] },
    { q: "What English word is pronounced differently when capitalized?", a: "Polish", wrong: ["Reading", "Desert"] },
    { q: "Which weighs more: a pound of feathers or a pound of bricks?", a: "They weigh the same", wrong: ["Bricks", "Feathers"] },
    { q: "What goes from Z to A?", a: "A zebra", wrong: ["The alphabet backward", "A zipper"] },
    { q: "What has a bark but no bite?", a: "A tree", wrong: ["A dog", "A seal"] },
    { q: "What has many eyes but cannot see?", a: "A potato", wrong: ["A storm", "A needle"] },
    { q: "What is black when it's clean and white when it's dirty?", a: "A blackboard", wrong: ["A whiteboard", "Coal"] },
    { q: "What has one head, one foot, and four legs?", a: "A bed", wrong: ["A table", "A dog"] },
    { q: "What goes up as soon as the rain comes down?", a: "An umbrella", wrong: ["A flower", "A worm"] },
    { q: "What loses its head in the morning and gets it back at night?", a: "A pillow", wrong: ["A ghost", "A dreamer"] },
    { q: "Which vehicle is spelled the same forwards and backwards?", a: "Racecar", wrong: ["Kayak", "Civic"] },
    { q: "What is at the end of a rainbow?", a: "The letter W", wrong: ["Gold", "Purple"] },
    { q: "What starts with P, ends with E, and has thousands of letters?", a: "The post office", wrong: ["A poem", "A page"] },
    { q: "Two fathers and two sons go fishing. They catch 3 fish and each gets one. How?", a: "Grandfather, father, son", wrong: ["One fish was shared", "They caught 4"] },
    { q: "What 5-letter word has one left when two are removed?", a: "Stone", wrong: ["Phone", "Alone"] },
    { q: "What kind of tree can you carry in your hand?", a: "A palm", wrong: ["A bonsai", "A sapling"] },
    { q: "What is easy to get into but hard to get out of?", a: "Trouble", wrong: ["A car", "A bed"] },
    { q: "Paul's height is six feet, he's an assistant at a butcher's shop, and wears size 9 shoes. What does he weigh?", a: "Meat", wrong: ["200 pounds", "180 pounds"] },
    { q: "What is the only word in the English language that is 9 letters long and remains a word at each step when you remove one letter at a time?", a: "Startling", wrong: ["Meaningful", "Beautiful"] },
    { q: "I have lakes with no water, mountains with no stone, and cities with no buildings. What am I?", a: "A map", wrong: ["A dream", "A globe"] },
    { q: "What is harder to catch the faster you run?", a: "Your breath", wrong: ["The wind", "A cold"] },
    { q: "What enters the water black and comes out red?", a: "A lobster", wrong: ["Iron", "Coal"] },
    { q: "I am a seed with three letters in my name. Take away the last two and I still sound the same. What am I?", a: "A pea", wrong: ["A bee", "Tea"] },
    { q: "What word is looking at you?", a: "Eye", wrong: ["See", "Look"] },
    { q: "I have no voice, but I can tell you a story. I have a spine, but no bones. What am I?", a: "A book", wrong: ["A movie", "A storyteller"] },
    { q: "What flies without wings?", a: "Time", wrong: ["A cloud", "A kite"] },
    { q: "I am light as a feather, yet the strongest man can't hold me for much more than a minute. What am I?", a: "Breath", wrong: ["Smoke", "A bubble"] },
    { q: "What connects two people but touches only one?", a: "A wedding ring", wrong: ["Phone call", "A kiss"] },
    { q: "I am the beginning of everything, the end of everywhere. I'm the beginning of eternity, the end of time and space.", a: "The letter E", wrong: ["God", "Space"] },
    { q: "What is 3/7 chicken, 2/3 cat, and 2/4 goat?", a: "Chicago", wrong: ["An animal", "A farm"] },
    { q: "What gets wetter and wetter the more it dries?", a: "A towel", wrong: ["A sponge", "Water"] },
    { q: "What sits in a corner while traveling around the world?", a: "A stamp", wrong: ["A globe", "A suitcase"] },
    { q: "What can you break, even if you never pick it up or touch it?", a: "A promise", wrong: ["A heart", "Glass"] },
    { q: "What goes through cities and fields but never moves?", a: "A road", wrong: ["A river", "A fence"] },
    { q: "I am always hungry, I must always be fed. The finger I lick will soon turn red. What am I?", a: "Fire", wrong: ["A baby", "A monster"] },
    { q: "People make me, save me, change me, raise me. What am I?", a: "Money", wrong: ["A child", "A house"] },
    { q: "What breaks yet never falls, and what falls yet never breaks?", a: "Day and Night", wrong: ["Rain and Glass", "Hearts and Dreams"] },
    { q: "I turn once, what is out will not get in. I turn again, what is in will not get out. What am I?", a: "A key", wrong: ["A door", "A lock"] },
    { q: "What runs all around a backyard, yet never moves?", a: "A fence", wrong: ["A dog", "Grass"] },
    { q: "What question can you never answer yes to?", a: "Are you asleep?", wrong: ["Are you hungry?", "Are you happy?"] },
    { q: "What has a thumb and four fingers but is not a hand?", a: "A glove", wrong: ["A foot", "A robot"] },
    { q: "What has a face and two hands but no arms or legs?", a: "A clock", wrong: ["A doll", "A robot"] },
    { q: "What is so fragile that saying its name breaks it?", a: "Silence", wrong: ["Glass", "A promise"] },
    { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", a: "The letter M", wrong: ["A chance", "A second"] },
    { q: "I have keys but no locks. I have space but no room. You can enter but you can't go inside. What am I?", a: "A keyboard", wrong: ["A piano", "A house"] },
    { q: "What is full of holes but still holds water?", a: "A sponge", wrong: ["A bucket", "A net"] },
    { q: "What gets broken without being held?", a: "A promise", wrong: ["A glass", "A heart"] },
    { q: "What has to be broken before you can use it?", a: "An egg", wrong: ["A glowstick", "A piñata"] },
    { q: "What goes up but never comes down?", a: "Your age", wrong: ["A balloon", "Smoke"] },
    { q: "The more of this there is, the less you see. What is it?", a: "Darkness", wrong: ["Fog", "Light"] },
    { q: "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", a: "An echo", wrong: ["A ghost", "A radio"] },
    { q: "The more you take, the more you leave behind. What am I?", a: "Footsteps", wrong: ["Memories", "Fingerprints"] },
    { q: "What has a neck but no head?", a: "A shirt", wrong: ["A giraffe", "A salesman"] },
    { q: "What has 13 hearts but no other organs?", a: "A deck of cards", wrong: ["A hospital", "A monster"] },
    { q: "What word becomes shorter when you add two letters?", a: "Short", wrong: ["Small", "Tiny"] }
];

const hardTrivia = [
    // World History
    { q: "In which year did the Berlin Wall fall?", a: "1989", wrong: ["1991", "1987", "1985"] },
    { q: "Who was the first Emperor of Rome?", a: "Augustus", wrong: ["Julius Caesar", "Nero", "Caligula"] },
    { q: "Which war was fought between the Houses of Lancaster and York?", a: "The Wars of the Roses", wrong: ["The Hundred Years' War", "The English Civil War", "The Barons' War"] },
    { q: "What ancient wonder was located in Alexandria?", a: "The Lighthouse", wrong: ["The Hanging Gardens", "The Colossus", "The Great Library"] },
    { q: "Who led the Bolshevik Revolution in 1917?", a: "Vladimir Lenin", wrong: ["Joseph Stalin", "Leon Trotsky", "Karl Marx"] },
    { q: "The Treaty of Westphalia in 1648 ended which major conflict?", a: "The Thirty Years' War", wrong: ["The Hundred Years' War", "The Seven Years' War", "The Napoleonic Wars"] },
    { q: "Which civilization built Machu Picchu?", a: "The Inca", wrong: ["The Aztec", "The Maya", "The Olmec"] },
    { q: "What was the name of the ship Darwin sailed on?", a: "HMS Beagle", wrong: ["HMS Victory", "HMS Endeavour", "HMS Discovery"] },
    { q: "Who was the last Pharaoh of ancient Egypt?", a: "Cleopatra VII", wrong: ["Ramesses II", "Tutankhamun", "Nefertiti"] },
    { q: "The Magna Carta was signed in which year?", a: "1215", wrong: ["1066", "1348", "1492"] },
    { q: "Which empire was ruled by Suleiman the Magnificent?", a: "Ottoman Empire", wrong: ["Persian Empire", "Mughal Empire", "Byzantine Empire"] },
    { q: "What event is known as the 'Shot Heard Round the World'?", a: "The Battle of Lexington", wrong: ["The assassination of Archduke Franz Ferdinand", "The fall of the Berlin Wall", "Pearl Harbor"] },

    // Science & Technology
    { q: "What is the speed of light in a vacuum, approximately?", a: "300,000 km/s", wrong: ["150,000 km/s", "500,000 km/s", "1,000,000 km/s"] },
    { q: "What is the most abundant gas in Earth's atmosphere?", a: "Nitrogen", wrong: ["Oxygen", "Carbon dioxide", "Argon"] },
    { q: "Who proposed the theory of general relativity?", a: "Albert Einstein", wrong: ["Isaac Newton", "Niels Bohr", "Max Planck"] },
    { q: "What is the chemical symbol for gold?", a: "Au", wrong: ["Ag", "Fe", "Go"] },
    { q: "What particle has a positive charge in an atom?", a: "Proton", wrong: ["Electron", "Neutron", "Photon"] },
    { q: "What is the powerhouse of the cell?", a: "Mitochondria", wrong: ["Nucleus", "Ribosome", "Golgi apparatus"] },
    { q: "What planet has the Great Red Spot?", a: "Jupiter", wrong: ["Mars", "Saturn", "Neptune"] },
    { q: "What is the half-life of Carbon-14, approximately?", a: "5,730 years", wrong: ["1,200 years", "10,500 years", "50,000 years"] },
    { q: "Who discovered penicillin?", a: "Alexander Fleming", wrong: ["Louis Pasteur", "Joseph Lister", "Robert Koch"] },
    { q: "What is the hardest natural substance on Earth?", a: "Diamond", wrong: ["Titanium", "Quartz", "Tungsten"] },
    { q: "Which element has the atomic number 1?", a: "Hydrogen", wrong: ["Helium", "Lithium", "Carbon"] },
    { q: "What is the study of fungi called?", a: "Mycology", wrong: ["Botany", "Virology", "Entomology"] },

    // Geography
    { q: "What is the smallest country in the world by area?", a: "Vatican City", wrong: ["Monaco", "San Marino", "Liechtenstein"] },
    { q: "What is the longest river in South America?", a: "Amazon", wrong: ["Nile", "Paraná", "Orinoco"] },
    { q: "Which country has the most natural lakes?", a: "Canada", wrong: ["Finland", "Russia", "United States"] },
    { q: "What is the capital of Mongolia?", a: "Ulaanbaatar", wrong: ["Astana", "Bishkek", "Tashkent"] },
    { q: "What is the deepest point in the ocean?", a: "Mariana Trench", wrong: ["Puerto Rico Trench", "Java Trench", "Tonga Trench"] },
    { q: "Which desert is the largest hot desert in the world?", a: "Sahara", wrong: ["Arabian", "Gobi", "Kalahari"] },
    { q: "What country is home to the world's highest waterfall?", a: "Venezuela", wrong: ["Brazil", "Zimbabwe", "Canada"] },
    { q: "Which strait separates Europe from Africa?", a: "Strait of Gibraltar", wrong: ["Strait of Hormuz", "Bosphorus", "Strait of Malacca"] },
    { q: "What is the capital of New Zealand?", a: "Wellington", wrong: ["Auckland", "Christchurch", "Sydney"] },
    { q: "Mount Kilimanjaro is located in which country?", a: "Tanzania", wrong: ["Kenya", "Ethiopia", "Uganda"] },
    { q: "What is the largest island in the world?", a: "Greenland", wrong: ["Madagascar", "Borneo", "New Guinea"] },
    { q: "Which European country has the most UNESCO World Heritage Sites?", a: "Italy", wrong: ["Spain", "France", "Germany"] },

    // Literature & Arts
    { q: "Who wrote 'One Hundred Years of Solitude'?", a: "Gabriel García Márquez", wrong: ["Jorge Luis Borges", "Pablo Neruda", "Isabel Allende"] },
    { q: "Which artist painted 'The Starry Night'?", a: "Vincent van Gogh", wrong: ["Claude Monet", "Pablo Picasso", "Salvador Dalí"] },
    { q: "Who composed 'The Four Seasons'?", a: "Antonio Vivaldi", wrong: ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven"] },
    { q: "What is the longest novel ever written by word count?", a: "In Search of Lost Time", wrong: ["War and Peace", "Les Misérables", "Don Quixote"] },
    { q: "Who wrote 'The Divine Comedy'?", a: "Dante Alighieri", wrong: ["Giovanni Boccaccio", "Petrarch", "Virgil"] },
    { q: "Which Shakespeare play features the character Prospero?", a: "The Tempest", wrong: ["A Midsummer Night's Dream", "The Merchant of Venice", "King Lear"] },
    { q: "Who painted the ceiling of the Sistine Chapel?", a: "Michelangelo", wrong: ["Leonardo da Vinci", "Raphael", "Caravaggio"] },
    { q: "What novel begins with 'Call me Ishmael'?", a: "Moby-Dick", wrong: ["The Old Man and the Sea", "Treasure Island", "Robinson Crusoe"] },
    { q: "Who wrote 'Crime and Punishment'?", a: "Fyodor Dostoevsky", wrong: ["Leo Tolstoy", "Anton Chekhov", "Ivan Turgenev"] },
    { q: "Which art movement is Salvador Dalí associated with?", a: "Surrealism", wrong: ["Cubism", "Impressionism", "Pop Art"] },
    { q: "Who composed the opera 'The Ring of the Nibelung'?", a: "Richard Wagner", wrong: ["Giuseppe Verdi", "Giacomo Puccini", "Wolfgang Mozart"] },
    { q: "What is the name of Jay Gatsby's love interest in 'The Great Gatsby'?", a: "Daisy Buchanan", wrong: ["Jordan Baker", "Myrtle Wilson", "Catherine"] },

    // Pop Culture & Entertainment
    { q: "What is the highest-grossing film of all time (not adjusted for inflation)?", a: "Avatar", wrong: ["Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"] },
    { q: "Which band released the album 'Dark Side of the Moon'?", a: "Pink Floyd", wrong: ["Led Zeppelin", "The Beatles", "The Rolling Stones"] },
    { q: "In 'The Matrix', what color pill does Neo take?", a: "Red", wrong: ["Blue", "Green", "White"] },
    { q: "Who directed 'Pulp Fiction'?", a: "Quentin Tarantino", wrong: ["Martin Scorsese", "David Fincher", "Christopher Nolan"] },
    { q: "What TV show features a chemistry teacher turned drug manufacturer?", a: "Breaking Bad", wrong: ["Ozark", "Narcos", "Better Call Saul"] },
    { q: "Which video game franchise features a character named Master Chief?", a: "Halo", wrong: ["Call of Duty", "Gears of War", "Destiny"] },
    { q: "Who played the Joker in 'The Dark Knight'?", a: "Heath Ledger", wrong: ["Jack Nicholson", "Jared Leto", "Joaquin Phoenix"] },
    { q: "What year was the first iPhone released?", a: "2007", wrong: ["2005", "2008", "2006"] },
    { q: "Which artist has the most Grammy Awards of all time?", a: "Beyoncé", wrong: ["Georg Solti", "Quincy Jones", "Stevie Wonder"] },
    { q: "In which fictional country is 'Black Panther' set?", a: "Wakanda", wrong: ["Zamunda", "Genovia", "Latveria"] },
    { q: "What is the name of the artificial intelligence in '2001: A Space Odyssey'?", a: "HAL 9000", wrong: ["WOPR", "Skynet", "JARVIS"] },
    { q: "Which rock band is known for the song 'Bohemian Rhapsody'?", a: "Queen", wrong: ["The Beatles", "Led Zeppelin", "The Rolling Stones"] },

    // Sports & Athletics
    { q: "How many players are on a rugby union team?", a: "15", wrong: ["13", "11", "18"] },
    { q: "In which sport would you perform a 'triple axel'?", a: "Figure skating", wrong: ["Gymnastics", "Diving", "Skateboarding"] },
    { q: "Which country has won the most FIFA World Cup titles?", a: "Brazil", wrong: ["Germany", "Italy", "Argentina"] },
    { q: "What is the only Grand Slam tennis tournament played on clay?", a: "French Open", wrong: ["Australian Open", "Wimbledon", "US Open"] },
    { q: "How long is a marathon in miles?", a: "26.2 miles", wrong: ["24.5 miles", "28.1 miles", "25.0 miles"] },
    { q: "Which boxer was known as 'The Greatest'?", a: "Muhammad Ali", wrong: ["Mike Tyson", "Floyd Mayweather", "Joe Louis"] },
    { q: "In which sport is the Stanley Cup awarded?", a: "Ice hockey", wrong: ["Football", "Baseball", "Basketball"] },
    { q: "What country invented the sport of cricket?", a: "England", wrong: ["India", "Australia", "South Africa"] },
    { q: "How many holes are played in a standard round of golf?", a: "18", wrong: ["9", "12", "21"] },
    { q: "Which swimmer has won the most Olympic gold medals?", a: "Michael Phelps", wrong: ["Mark Spitz", "Ian Thorpe", "Ryan Lochte"] },
    { q: "In baseball, how many strikes make an out?", a: "Three", wrong: ["Two", "Four", "Five"] },
    { q: "Which Formula 1 driver holds the record for most World Championships?", a: "Michael Schumacher and Lewis Hamilton (tied)", wrong: ["Ayrton Senna", "Sebastian Vettel", "Alain Prost"] },

    // Mathematics & Logic
    { q: "What is the only even prime number?", a: "2", wrong: ["4", "0", "6"] },
    { q: "What is the value of Pi to two decimal places?", a: "3.14", wrong: ["3.16", "3.12", "3.18"] },
    { q: "What is the Fibonacci sequence's 7th number (starting from 0)?", a: "13", wrong: ["8", "11", "21"] },
    { q: "What is the sum of all angles in a triangle?", a: "180 degrees", wrong: ["360 degrees", "90 degrees", "270 degrees"] },
    { q: "What is the square root of 144?", a: "12", wrong: ["14", "11", "13"] },
    { q: "What is the mathematical term for a polygon with eight sides?", a: "Octagon", wrong: ["Hexagon", "Heptagon", "Nonagon"] },
    { q: "Who is considered the father of geometry?", a: "Euclid", wrong: ["Pythagoras", "Archimedes", "Aristotle"] },
    { q: "What does the Roman numeral 'M' represent?", a: "1000", wrong: ["500", "5000", "100"] },
    { q: "What is the name for a number that can only be divided by 1 and itself?", a: "Prime number", wrong: ["Composite number", "Perfect number", "Rational number"] },
    { q: "What is 2 to the power of 10?", a: "1024", wrong: ["512", "2048", "1000"] },
    { q: "How many degrees are in a circle?", a: "360", wrong: ["180", "270", "400"] },
    { q: "What famous theorem relates the sides of a right triangle?", a: "Pythagorean theorem", wrong: ["Fermat's theorem", "Euler's theorem", "Bernoulli's theorem"] },

    // Philosophy & Psychology
    { q: "'I think, therefore I am' was stated by which philosopher?", a: "René Descartes", wrong: ["Socrates", "Immanuel Kant", "Friedrich Nietzsche"] },
    { q: "What is Maslow's highest level of the hierarchy of needs?", a: "Self-actualization", wrong: ["Esteem", "Love and belonging", "Safety"] },
    { q: "Who wrote 'The Republic'?", a: "Plato", wrong: ["Aristotle", "Socrates", "Homer"] },
    { q: "What psychological phenomenon describes conforming to group pressure?", a: "Groupthink", wrong: ["Cognitive dissonance", "Confirmation bias", "Halo effect"] },
    { q: "Who is considered the father of psychoanalysis?", a: "Sigmund Freud", wrong: ["Carl Jung", "B.F. Skinner", "William James"] },
    { q: "What philosophical thought experiment involves a cat that is both alive and dead?", a: "Schrödinger's cat", wrong: ["Pavlov's dog", "Russell's teapot", "Maxwell's demon"] },
    { q: "Which philosopher wrote 'Thus Spoke Zarathustra'?", a: "Friedrich Nietzsche", wrong: ["Arthur Schopenhauer", "Georg Hegel", "Søren Kierkegaard"] },
    { q: "What is the term for fear of open spaces?", a: "Agoraphobia", wrong: ["Claustrophobia", "Acrophobia", "Xenophobia"] },
    { q: "Which ancient Greek philosopher was a student of Plato?", a: "Aristotle", wrong: ["Socrates", "Epicurus", "Diogenes"] },
    { q: "What is the 'trolley problem' primarily a question about?", a: "Ethics and moral dilemmas", wrong: ["Transportation", "Physics", "Economics"] },

    // Politics & Economics
    { q: "What is the term for a government ruled by a small group of powerful people?", a: "Oligarchy", wrong: ["Autocracy", "Democracy", "Theocracy"] },
    { q: "Who wrote 'The Wealth of Nations'?", a: "Adam Smith", wrong: ["Karl Marx", "John Maynard Keynes", "David Ricardo"] },
    { q: "What does GDP stand for?", a: "Gross Domestic Product", wrong: ["General Domestic Production", "Gross Developed Product", "Global Domestic Price"] },
    { q: "Which country was the first to grant women the right to vote?", a: "New Zealand", wrong: ["Finland", "United States", "United Kingdom"] },
    { q: "What economic system is characterized by private ownership and free markets?", a: "Capitalism", wrong: ["Socialism", "Communism", "Feudalism"] },
    { q: "Who was the first female Prime Minister of the United Kingdom?", a: "Margaret Thatcher", wrong: ["Theresa May", "Queen Victoria", "Elizabeth II"] },

    // Food & Cuisine
    { q: "What Japanese dish consists of vinegared rice with raw fish?", a: "Sushi", wrong: ["Sashimi", "Ramen", "Tempura"] },
    { q: "What spice gives curry its yellow color?", a: "Turmeric", wrong: ["Saffron", "Paprika", "Cumin"] },
    { q: "What country is the origin of the croissant?", a: "Austria", wrong: ["France", "Italy", "Belgium"] },
    { q: "What is the main ingredient in hummus?", a: "Chickpeas", wrong: ["Lentils", "Tahini", "Fava beans"] },
    { q: "Which Italian city is considered the birthplace of pizza?", a: "Naples", wrong: ["Rome", "Florence", "Milan"] },
    { q: "What is the world's most expensive spice by weight?", a: "Saffron", wrong: ["Vanilla", "Cardamom", "Cinnamon"] },
    { q: "What grain is sake made from?", a: "Rice", wrong: ["Barley", "Wheat", "Corn"] },
    { q: "Which country produces the most coffee in the world?", a: "Brazil", wrong: ["Colombia", "Vietnam", "Ethiopia"] },

    // Language & Etymology
    { q: "What is the most spoken language in the world by total speakers?", a: "English", wrong: ["Mandarin Chinese", "Spanish", "Hindi"] },
    { q: "What language has the most words?", a: "English", wrong: ["Mandarin Chinese", "Arabic", "Russian"] },
    { q: "What does 'veni, vidi, vici' mean?", a: "I came, I saw, I conquered", wrong: ["To be or not to be", "In wine there is truth", "Seize the day"] },
    { q: "What is the study of word origins called?", a: "Etymology", wrong: ["Entomology", "Epistemology", "Ethnology"] },
    { q: "How many official languages does the United Nations have?", a: "Six", wrong: ["Five", "Eight", "Four"] },
    { q: "What is the world's oldest known written language?", a: "Sumerian", wrong: ["Egyptian", "Chinese", "Sanskrit"] },

    // Nature & Animals
    { q: "What is the largest living organism on Earth?", a: "Honey fungus", wrong: ["Blue whale", "Giant sequoia", "Great Barrier Reef"] },
    { q: "How many hearts does an octopus have?", a: "Three", wrong: ["Two", "One", "Four"] },
    { q: "What animal has the longest migration?", a: "Arctic tern", wrong: ["Monarch butterfly", "Gray whale", "Wildebeest"] },
    { q: "What is the only mammal capable of true flight?", a: "Bat", wrong: ["Flying squirrel", "Sugar glider", "Colugo"] },
    { q: "What gas do plants absorb from the atmosphere?", a: "Carbon dioxide", wrong: ["Oxygen", "Nitrogen", "Hydrogen"] },
    { q: "What is the fastest bird in the world?", a: "Peregrine falcon", wrong: ["Golden eagle", "Cheetah", "Swift"] },
    { q: "How long does it take for light from the Sun to reach Earth?", a: "About 8 minutes", wrong: ["About 1 minute", "About 30 minutes", "About 1 second"] },
    { q: "What animal can regenerate its heart?", a: "Zebrafish", wrong: ["Starfish", "Salamander", "Axolotl"] },
    { q: "What percentage of the ocean floor has been explored?", a: "About 5%", wrong: ["About 25%", "About 50%", "About 10%"] },
    { q: "What is the largest species of shark?", a: "Whale shark", wrong: ["Great white shark", "Basking shark", "Hammerhead shark"] },
    { q: "What is the capital of Australia?", a: "Canberra", wrong: ["Sydney", "Melbourne"] },
    { q: "What is the chemical symbol for Silver?", a: "Ag", wrong: ["Si", "Au"] },
    { q: "Which is the smallest bone in the human body?", a: "Stapes (in the ear)", wrong: ["Femur", "Phalanges"] },
    { q: "What is the largest organ of the human body?", a: "Skin", wrong: ["Liver", "Heart"] },
    { q: "Who was the first woman in space?", a: "Valentina Tereshkova", wrong: ["Sally Ride", "Mae Jemison"] },
    { q: "In what year did the first man walk on the moon?", a: "1969", wrong: ["1965", "1971"] },
    { q: "Who wrote the play 'Hamlet'?", a: "William Shakespeare", wrong: ["Charles Dickens", "Mark Twain"] },
    { q: "What is the atomic number of Oxygen?", a: "8", wrong: ["6", "10"] },
    { q: "What is the hardest mineral known?", a: "Diamond", wrong: ["Quartz", "Granite"] },
    { q: "What is the approximate speed of sound in air?", a: "343 m/s", wrong: ["300,000 km/s", "100 km/h"] },
    { q: "What is the capital of Canada?", a: "Ottawa", wrong: ["Toronto", "Montreal"] },
    { q: "What is the capital of Brazil?", a: "Brasilia", wrong: ["Rio de Janeiro", "Sao Paulo"] },
    { q: "What is the longest river in the world?", a: "The Nile", wrong: ["The Amazon", "The Mississippi"] },
    { q: "How many bones are in the adult human body?", a: "206", wrong: ["200", "212"] },
    { q: "Which planet is the hottest in the solar system?", a: "Venus", wrong: ["Mercury", "Mars"] },
    { q: "How long did the Hundred Years' War last?", a: "116 years", wrong: ["100 years", "99 years"] },
    { q: "What were the Canary Islands named after?", a: "Dogs", wrong: ["Birds", "Cats"] },
    { q: "How many wives did King Henry VIII have?", a: "6", wrong: ["4", "8"] },
    { q: "Who painted 'The Scream'?", a: "Edvard Munch", wrong: ["Vincent van Gogh", "Pablo Picasso"] },
    { q: "Who wrote the novel '1984'?", a: "George Orwell", wrong: ["Aldous Huxley", "Ray Bradbury"] },
    { q: "Who directed 'Schindler's List'?", a: "Steven Spielberg", wrong: ["Martin Scorsese", "James Cameron"] },
    { q: "What are the four official languages of Switzerland?", a: "German, French, Italian, Romansh", wrong: ["German, French, English, Spanish", "German, French, Italian, Dutch"] },
    { q: "What is the largest desert in the world?", a: "Antarctic Desert", wrong: ["Sahara Desert", "Gobi Desert"] },
    { q: "Who cut off his own ear?", a: "Vincent van Gogh", wrong: ["Pablo Picasso", "Claude Monet"] },
    { q: "What is the main ingredient of glass?", a: "Sand (Silica)", wrong: ["Clay", "Stone"] },
    { q: "What is the most abundant element in the Sun?", a: "Hydrogen", wrong: ["Helium", "Oxygen"] },
    { q: "Which star is closest to Earth?", a: "The Sun", wrong: ["Proxima Centauri", "Sirius"] },
    { q: "How many teeth does an adult human usually have?", a: "32", wrong: ["30", "28"] },
    { q: "How many valves does a standard trumpet have?", a: "3", wrong: ["4", "2"] },
    { q: "What represents the letter 'K' in the periodic table?", a: "Potassium", wrong: ["Krypton", "Calcium"] },
    { q: "What is the currency of Japan?", a: "Yen", wrong: ["Won", "Yuan"] },
    { q: "Who wrote 'Pride and Prejudice'?", a: "Jane Austen", wrong: ["Charlotte Brontë", "Emily Brontë"] },
    { q: "What year did World War I begin?", a: "1914", wrong: ["1918", "1939"] },
    { q: "What is the boiling point of water in Fahrenheit?", a: "212 degrees", wrong: ["100 degrees", "200 degrees"] },
    { q: "Who discovered gravity?", a: "Isaac Newton", wrong: ["Albert Einstein", "Galileo Galilei"] },
    { q: "Which element is liquid at room temperature?", a: "Mercury", wrong: ["Iron", "Gold"] },
    { q: "What is the study of plants called?", a: "Botany", wrong: ["Zoology", "Geology"] },
    { q: "Which country gifted the Statue of Liberty to the USA?", a: "France", wrong: ["England", "Spain"] },
    { q: "What is the name of the fairy in Peter Pan?", a: "Tinker Bell", wrong: ["Cinderella", "Ariel"] },
    { q: "Who wrote The Lord of the Rings?", a: "J.R.R. Tolkien", wrong: ["C.S. Lewis", "J.K. Rowling"] },
    { q: "What is the largest planet in our solar system?", a: "Jupiter", wrong: ["Saturn", "Earth"] },
    { q: "Who painted the ceiling of the Sistine Chapel?", a: "Michelangelo", wrong: ["Leonardo da Vinci", "Raphael"] },
    { q: "What is the capital of Spain?", a: "Madrid", wrong: ["Barcelona", "Seville"] },
    { q: "What is the chemical formula for water?", a: "H2O", wrong: ["CO2", "O2"] },
    { q: "Which continent is the Sahara Desert in?", a: "Africa", wrong: ["Asia", "Australia"] },
    { q: "How many legs does a butterfly have?", a: "6", wrong: ["4", "8"] },
    { q: "What is the hardest natural substance?", a: "Diamond", wrong: ["Gold", "Iron"] },
    { q: "Who was the first President of the United States?", a: "George Washington", wrong: ["Abraham Lincoln", "Thomas Jefferson"] },
    { q: "Which ocean is the largest?", a: "Pacific Ocean", wrong: ["Atlantic Ocean", "Indian Ocean"] }
];
